module SatelicomPtv
  module Constant
    RESULT_FIELD = [
      :COUNTRY, :STATE, :ADMINREGION, :CITY, :CITY2, :POSTCODE, :STREET, :HOUSENR, 
      :COORDX, :COORDY, :DETAILLEVEL, :DETAILLEVEL_DESCRIPTION, :POPULATION, :EXTENSIONCLASS,
      :LEVEL, :ISCITYDISTRICT, :COUNTRY_ISO2, :COUNTRY_ISO3, :COUNTRY_COUNTRYCODEPLATE, 
      :COUNTRY_DIALINGCODE, :COUNTRY_CAPITAL, :COUNTRY_NAME, :HOUSENR_SIDE, :HOUSENR_STRUCTURE, 
      :HOUSENR_STARTFORMAT, :HOUSENR_ENDFORMAT, :APPENDIX, :SCORE_TOTALSCORE, :SCORE_FINALPENALTY, 
      :FOUNDBY_CITY, :FOUNDBY_CITY2, :FOUNDBY_POSTCODE, :FOUNDBY_STREET, :CLASSIFICATION, 
      :CLASSIFICATION_DESCRIPTION, :SWAPANDSPLITMODE, :POPUPINFO, :PHONENUMBER, :SEGMENT_ID, 
      :SEGMENT_COUNTRY, :SEGMENT_DIRECTION, :XYN, :POINAME, :POITYPE, :ADDRESS_CLASSIFICATION, 
      :ADDRESS_CLASSIFICATION_DESCRIPTION, :POSTCODE_CLASSIFICATION, :TOWN_CLASSIFICATION, 
      :STREET_CLASSIFICATION, :HOUSENR_CLASSIFICATION, :POSTCODE_CHARACTERISTICS, :TOWN_CHARACTERISTICS, 
      :STREET_CHARACTERISTICS, :HOUSENR_CHARACTERISTICS, :UNMATCHED_WORDS, :UNMATCHED_WORDS_COUNT, 
      :STREETX, :STREETY, :ADMINX, :ADMINY, :DESTINATION_LOCATION_NODE_N, :DESTINATION_LOCATION_NODE_Y,
      :DESTINATION_LOCATION_NODE_X, :DESTINATION_LOCATION_TILE_Y, :DESTINATION_LOCATION_TILE_X, 
      :DESTINATION_LOCATION_COUNTRYCODE, :START_LOCATION_NODE_N, :START_LOCATION_NODE_Y, 
      :START_LOCATION_NODE_X, :START_LOCATION_TILE_Y, :START_LOCATION_TILE_X, :START_LOCATION_COUNTRYCODE, 
      :ISBLOCKEDFORPEDESTRIANS, :ISBLOCKEDFORBICYCLES, :ISBLOCKEDFORMOTORCYCLES, :ISBLOCKEDFORCARS, 
      :ISBLOCKEDFORVANS, :ISBLOCKEDFORCAMPERS, :ISBLOCKEDFORBUSES, :ISBLOCKEDFORHAZARDOUSGOODS, 
      :ISBLOCKEDFORCOMBUSTIBLEGOODS, :ISBLOCKEDFORTRUCKS, :ARTIFICIALTOWNCHARACTERIZATION, 
      :CITY_LEVEL, :STREETNUMBER, :HOUSENR_ATINPUTCOORDINATESIDE, :PROVINCE 
    ]
    SORT_ORDER = [:ASCENDING, :DESCENDING]
  end
end
